sudo: required
dist: trusty
language: node_js
node_js:
  - "7.9.0"

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - npm install -g karma
  - npm install

script:
  - ng build
  - ng test

notifications:
  email:
    on_failure: change
    on_success: change